# Generated by Django 4.2.1 on 2023-05-17 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.IntegerField(choices=[(2, 'female'), (3, 'male')])),
                ('age', models.IntegerField(choices=[(2, '10s'), (3, '20s'), (4, '30s'), (5, '40s'), (6, '50s'), (7, '60s'), (8, '70s'), (9, '80s'), (10, '90s')])),
                ('marriage', models.IntegerField(choices=[(2, 'married'), (3, 'single'), (4, 'divorce'), (5, 'deceased')])),
                ('income', models.IntegerField(choices=[(2, '-1000'), (3, '1000-3000'), (4, '3000-5000'), (5, '5000-7000'), (6, '7000-10000'), (7, '10000-')])),
                ('education', models.IntegerField(choices=[(2, 'middle school'), (3, 'high school'), (4, 'bachelor'), (5, 'master'), (6, 'doctor')])),
                ('job', models.IntegerField(choices=[(2, 'public enterprise'), (3, 'teacher'), (4, 'profession'), (5, 'managerial'), (6, 'office'), (7, 'production'), (8, 'service'), (9, 'student')])),
                ('phone', models.IntegerField(choices=[(2, 'feature phone'), (3, 'smartphone'), (4, 'both'), (5, 'not use')])),
                ('phone_maker', models.IntegerField(choices=[(2, 'Samsung'), (3, 'LG'), (4, 'Apple')])),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
