# Generated by Django 4.2.1 on 2023-05-18 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personalinfo',
            name='age',
        ),
        migrations.RemoveField(
            model_name='personalinfo',
            name='education',
        ),
        migrations.RemoveField(
            model_name='personalinfo',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='personalinfo',
            name='income',
        ),
        migrations.RemoveField(
            model_name='personalinfo',
            name='job',
        ),
        migrations.RemoveField(
            model_name='personalinfo',
            name='marriage',
        ),
        migrations.RemoveField(
            model_name='personalinfo',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='personalinfo',
            name='phone_maker',
        ),
    ]
