# Generated by Django 4.2.1 on 2023-05-18 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0002_remove_personalinfo_age_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PersonalInfo',
            new_name='PersonalEmail',
        ),
    ]
